version: "3.8"
services:
    nodeserver:
        restart: always
        environment:
            - MONGO_URL
            - MONGOOSE_DEBUG
            - LEVEL
        build:
            context: .
        ports:
            - "5000:8000"
        links:
          - "mongo"
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - "27017:27017"